// Autogenerated from Pigeon (v22.4.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.mazrean.mouse_proto.platform

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class MouseMessage (
  val left: Boolean,
  val right: Boolean,
  val middle: Boolean,
  val x: Long,
  val y: Long,
  val wheel: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MouseMessage {
      val left = pigeonVar_list[0] as Boolean
      val right = pigeonVar_list[1] as Boolean
      val middle = pigeonVar_list[2] as Boolean
      val x = pigeonVar_list[3] as Long
      val y = pigeonVar_list[4] as Long
      val wheel = pigeonVar_list[5] as Long
      return MouseMessage(left, right, middle, x, y, wheel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      left,
      right,
      middle,
      x,
      y,
      wheel,
    )
  }
}
private open class BluetoothHIDApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MouseMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MouseMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface BluetoothHIDApi {
  fun sendMouseMessage(message: MouseMessage, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by BluetoothHIDApi. */
    val codec: MessageCodec<Any?> by lazy {
      BluetoothHIDApiPigeonCodec()
    }
    /** Sets up an instance of `BluetoothHIDApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: BluetoothHIDApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mouse_proto.BluetoothHIDApi.sendMouseMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as MouseMessage
            api.sendMouseMessage(messageArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
